services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_DB: exchangeratedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - backend

  rate-service:
    build:
      context: ./rate-service
      dockerfile: Dockerfile
    image: clementdevv/exchange-rate-services:rate-service
    ports:
      - "8081:8081"
    depends_on: []
    env_file:
      - ./.env
    networks:
      - backend

  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    image: clementdevv/exchange-rate-services:main-service
    ports:
      - "8080:8080"
    depends_on:
      - rate-service
      - postgres-db
    env_file:
      - ./.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
