## Use Amazon Corretto 21 as the base image
#FROM eclipse-temurin:17-jdk-jammy
#
## Set the working directory inside the container
#WORKDIR /app
#
## Copy the JAR file into the container
#COPY target/main-service-*.jar app.jar
#
#EXPOSE 8080
#
## Set the entry point to run the JAR file
#CMD ["java", "-jar", "rate_service.jar"]
