spring.application.name=rate-service
server.port=8081

# Exchange Rate API Properties
# Make sure these match exactly what's expected in ExchangeApiProperties class
exchange-rate-api.base-url=https://api.exchangeratesapi.io
exchange-rate-api.key=16a02c47f248542bf43696141dab3f36

# Add debug logging for Spring
logging.level.org.springframework.web=DEBUG
logging.level.com.clementdevv=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration